In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
inspection_score_with_tracs = pd.read_csv('https://raw.githubusercontent.com/bestkb/HUD-Public-Housing/main/data/locations_inspectionscores_w_tracts.csv')
inspection_score_with_tracs

,DEVELOPMENT_ID,DEVELOPMENT_NAME,CBSA_CODE,COUNTY_NAME,COUNTY_CODE,STATE_NAME.x,STATE_CODE,ZIPCODE,LATITUDE,LONGITUDE,PHA_CODE,INSPECTION_SCORE,FloodDistM,in_floodplain,census_code,block_group,county,inspection_year,tract
0,LA130000001,Duson Housing Authority,29180.0,Lafayette,55.0,LA,22,70529.0,30.239980,-92.180929,LA130,66.0,2992.337961,0.0,2.205500e+14,2.205500e+11,22055.0,2013.0,2.205500e+10
1,GA006000772,CENTENNIAL PLACE III,12060.0,Fulton,121.0,GA,13,30313.0,33.768702,-84.394727,GA006,91.0,14016.674280,0.0,1.312100e+14,1.312100e+11,13121.0,2013.0,1.312100e+10
2,GA006000770,CENTENNIAL PLACE I,12060.0,Fulton,121.0,GA,13,30313.0,33.768652,-84.392906,GA006,90.0,13985.890300,0.0,1.312100e+14,1.312100e+11,13121.0,2013.0,1.312100e+10
3,DC001001830,SCATTERED SITES,47900.0,District Of Columbia,1.0,DC,11,20001.0,38.906725,-77.014991,DC001,69.0,4377.215324,0.0,1.100100e+14,1.100100e+11,11001.0,2014.0,1.100100e+10
4,CA019000180,SCATTERED SITES,40140.0,San Bernardino,71.0,CA,6,92307.0,34.511681,-117.179101,CA019,84.0,366145.436500,0.0,6.071010e+13,6.071010e+10,6071.0,2013.0,6.071010e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53759,WI214000001,STOUGHTON HSG/SCAT SITES,31540.0,Dane,25.0,WI,55,53589.0,42.915667,-89.200444,WI214,41.0,8111.980157,0.0,5.502501e+14,5.502501e+11,55025.0,2020.0,5.502501e+10
53760,WV011000001,DORSEY ST/BURLEY/FRANCINE/KERMIT/GATTSCT,48540.0,Marshall,51.0,WV,54,26041.0,39.916098,-80.746791,WV011,74.0,151.172824,0.0,5.405102e+14,5.405102e+11,54051.0,2020.0,5.405102e+10
53761,PA001000044,FINELLO PAVILION,38300.0,Allegheny,3.0,PA,42,15213.0,40.434161,-79.960029,PA001,57.0,16956.412360,0.0,4.200304e+14,4.200304e+11,42003.0,2020.0,4.200304e+10
53762,LA013000013,ACRE ROAD PROJECT,35380.0,Jefferson,51.0,LA,22,70072.0,29.886046,-90.116897,LA013,56.0,2487.236365,0.0,2.205103e+14,2.205103e+11,22051.0,2020.0,2.205103e+10
53763,TN040000001,WILLOW COURTS,99999.0,Henderson,77.0,TN,47,38351.0,35.655754,-88.403674,TN040,87.0,315.973737,0.0,4.707798e+14,4.707798e+11,47077.0,2020.0,4.707798e+10

In [9]:
raw_county_data = pd.read_csv('https://raw.githubusercontent.com/bestkb/HUD-Public-Housing/main/data/raw_county_data.csv')
raw_county_data

,GEOID,age_c,total_pop_c,total_white_c,total_black_c,total_hispanic_c,poverty_c,income_c,public_assistance_c,owner_c,renter_c,vehicles_c,prop_value_c,year
0,1001,36.0,49584,38636,8827,1012,13305.0,51463.0,18288.0,14182,4106,18288,130700.0,2009
1,1003,41.0,171997,146381,16851,4989,49464.0,48918.0,68497.0,53056,15441,68497,173100.0,2009
2,1005,37.5,29663,14251,13724,1262,7430.0,32537.0,10645.0,7079,3566,10645,83400.0,2009
3,1007,38.6,21464,16182,4953,190,5582.0,41236.0,7525.0,5915,1610,7525,81300.0,2009
4,1009,38.2,56804,50787,473,4134,14213.0,45406.0,19228.0,15929,3299,19228,109700.0,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38641,72145,42.4,51089,1347,8,49596,13318.0,20126.0,19343.0,14974,4369,19343,105000.0,2020
38642,72147,43.8,8508,520,28,7960,1340.0,14040.0,2405.0,1690,715,2405,97500.0,2020
38643,72149,41.3,21899,36,17,21846,5844.0,19355.0,7932.0,5684,2248,7932,91200.0,2020
38644,72151,44.1,32867,22,0,32845,7739.0,16828.0,11687.0,8387,3300,11687,87000.0,2020
38645,72153,45.1,34501,138,23,34179,7353.0,14813.0,11654.0,8695,2959,11654,91700.0,2020

In [10]:
raw_tract_data = pd.read_csv('https://raw.githubusercontent.com/bestkb/HUD-Public-Housing/main/data/raw_tract_data.csv')
raw_tract_data

,GEOID,age,total_pop,total_white,total_black,total_hispanic,poverty,income,public_assistance,owner,renter,vehicles,prop_value,year
0,22001960100,36.1,6541,4436,1983,61,1780.0,26335.0,2613.0,1555,1058,2613,71100.0,2009
1,22001960200,40.5,4827,4454,226,44,1452.0,48306.0,1908.0,1435,473,1908,102800.0,2009
2,22001960300,37.4,3679,3568,30,24,968.0,47097.0,1192.0,1084,108,1192,63100.0,2009
3,22001960400,32.2,5878,5539,263,0,1456.0,38401.0,2016.0,1568,448,2016,86800.0,2009
4,22001960500,35.7,5429,4933,403,93,1544.0,54547.0,1927.0,1684,243,1927,97300.0,2009
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880431,56043000200,48.9,3124,2900,1,171,1021.0,55268.0,1333.0,1027,306,1333,217200.0,2020
880432,56043000301,37.1,2231,1611,0,459,577.0,52074.0,1053.0,708,345,1053,139200.0,2020
880433,56043000302,37.6,2578,1976,0,504,682.0,65543.0,1051.0,775,276,1051,170500.0,2020
880434,56045951100,48.4,3276,2885,44,77,962.0,51694.0,1386.0,1170,216,1386,183800.0,2020
880435,56045951300,38.2,3666,3408,0,56,1017.0,57717.0,1496.0,1249,247,1496,153700.0,2020

In [11]:
locations_inspectionscores = pd.read_csv('https://raw.githubusercontent.com/bestkb/HUD-Public-Housing/main/data/tract_demographics_forMeri_Feb.csv')
locations_inspectionscores

,DEVELOPMENT_ID,block_group,county,tract,age_c,total_pop_c,total_white_c,total_black_c,total_hispanic_c,poverty_c,income_c,public_assistance_c,owner_c,renter_c,vehicles_c,prop_value_c,year
0,LA130000001,2.205500e+11,22055.0,2.205500e+10,34.9,4807.0,2821.0,1895.0,0.0,1187.0,34310.0,1942.0,1439.0,503.0,1942.0,82100.0,2010.0
1,LA130000001,2.205500e+11,22055.0,2.205500e+10,33.7,4952.0,2989.0,1828.0,1.0,1194.0,32292.0,1922.0,1371.0,551.0,1922.0,86600.0,2011.0
2,LA130000001,2.205500e+11,22055.0,2.205500e+10,31.9,5429.0,3146.0,1835.0,132.0,1367.0,36383.0,2023.0,1443.0,580.0,2023.0,94400.0,2012.0
3,LA130000001,2.205500e+11,22055.0,2.205500e+10,30.8,5830.0,3322.0,1995.0,137.0,1554.0,38233.0,2064.0,1470.0,594.0,2064.0,94800.0,2013.0
4,LA130000001,2.205500e+11,22055.0,2.205500e+10,29.6,5743.0,3473.0,1797.0,136.0,1523.0,50119.0,1952.0,1373.0,579.0,1952.0,97300.0,2014.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101789,OH001000236,3.904900e+11,39049.0,3.904900e+10,37.9,1796.0,342.0,1283.0,38.0,389.0,34331.0,805.0,362.0,443.0,805.0,61700.0,2016.0
101790,OH001000236,3.904900e+11,39049.0,3.904900e+10,39.8,1955.0,447.0,1291.0,12.0,434.0,36442.0,918.0,412.0,506.0,918.0,58400.0,2017.0
101791,OH001000236,3.904900e+11,39049.0,3.904900e+10,37.6,2233.0,489.0,1507.0,42.0,448.0,34259.0,948.0,306.0,642.0,948.0,57900.0,2018.0
101792,OH001000236,3.904900e+11,39049.0,3.904900e+10,37.2,2132.0,526.0,1439.0,31.0,408.0,32940.0,944.0,306.0,638.0,944.0,175900.0,2019.0
101793,OH001000236,3.904900e+11,39049.0,3.904900e+10,38.4,2162.0,629.0,1325.0,12.0,299.0,35577.0,1028.0,390.0,638.0,1028.0,176500.0,2020.0

In [12]:
tract_demographics = pd.read_csv('https://raw.githubusercontent.com/bestkb/HUD-Public-Housing/main/data/locations_inspectionscores_forMeri_Feb.csv')
tract_demographics

,DEVELOPMENT_ID,DEVELOPMENT_NAME,CBSA_CODE,COUNTY_NAME,COUNTY_CODE,STATE_NAME.x,STATE_CODE,ZIPCODE,LATITUDE,LONGITUDE,PHA_CODE,INSPECTION_SCORE,FloodDistM,in_floodplain,census_code,block_group,county,inspection_year
0,LA130000001,Duson Housing Authority,29180.0,Lafayette,55.0,LA,22,70529.0,30.239980,-92.180929,LA130,66.0,2992.337961,0.0,2.205500e+14,2.205500e+11,22055.0,2013.0
1,GA006000772,CENTENNIAL PLACE III,12060.0,Fulton,121.0,GA,13,30313.0,33.768702,-84.394727,GA006,91.0,14016.674280,0.0,1.312100e+14,1.312100e+11,13121.0,2013.0
2,GA006000770,CENTENNIAL PLACE I,12060.0,Fulton,121.0,GA,13,30313.0,33.768652,-84.392906,GA006,90.0,13985.890300,0.0,1.312100e+14,1.312100e+11,13121.0,2013.0
3,DC001001830,SCATTERED SITES,47900.0,District Of Columbia,1.0,DC,11,20001.0,38.906725,-77.014991,DC001,69.0,4377.215324,0.0,1.100100e+14,1.100100e+11,11001.0,2014.0
4,CA019000180,SCATTERED SITES,40140.0,San Bernardino,71.0,CA,6,92307.0,34.511681,-117.179101,CA019,84.0,366145.436500,0.0,6.071010e+13,6.071010e+10,6071.0,2013.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53759,WI214000001,STOUGHTON HSG/SCAT SITES,31540.0,Dane,25.0,WI,55,53589.0,42.915667,-89.200444,WI214,41.0,8111.980157,0.0,5.502501e+14,5.502501e+11,55025.0,2020.0
53760,WV011000001,DORSEY ST/BURLEY/FRANCINE/KERMIT/GATTSCT,48540.0,Marshall,51.0,WV,54,26041.0,39.916098,-80.746791,WV011,74.0,151.172824,0.0,5.405102e+14,5.405102e+11,54051.0,2020.0
53761,PA001000044,FINELLO PAVILION,38300.0,Allegheny,3.0,PA,42,15213.0,40.434161,-79.960029,PA001,57.0,16956.412360,0.0,4.200304e+14,4.200304e+11,42003.0,2020.0
53762,LA013000013,ACRE ROAD PROJECT,35380.0,Jefferson,51.0,LA,22,70072.0,29.886046,-90.116897,LA013,56.0,2487.236365,0.0,2.205103e+14,2.205103e+11,22051.0,2020.0
53763,TN040000001,WILLOW COURTS,99999.0,Henderson,77.0,TN,47,38351.0,35.655754,-88.403674,TN040,87.0,315.973737,0.0,4.707798e+14,4.707798e+11,47077.0,2020.0

In [ ]:
# over time (data available) the mean inspection score in the us