In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv

#number of decimals to keep
NUM_DECIMAL = 2

#header for year
HEADER_YEAR = ['year', 'count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']

#fema region
FEMA_MAP = {
    #Connecticut | Maine | Massachusetts | New Hampshire | Rhode Island | Vermont
    'region1': ['CT', 'ME', 'MA', 'NH', 'RI', 'VT'], 
    #New Jersey | New York | Puerto Rico | Virgin Islands
    'region2': ['NJ', 'NY', 'PR', 'VI'],
    #Delaware | Maryland | Pennsylvania | Virginia | District of Columbia | West Virginia
    'region3': ['DE', 'MD', 'PA', 'VA', 'DC', 'WV'],
    #Alabama | Florida | Georgia | Kentucky |  Mississippi | North Carolina | South Carolina | Tennessee
    'region4': ['AL', 'FL', 'GA', 'KY', 'MS', 'NC', 'SC', 'TN'], 
    #Illinois | Indiana | Michigan | Minnesota | Ohio | Wisconsin
    'region5': ['IL', 'IN', 'MI', 'MN','OH', 'WI'],
    #Arkansas | Louisiana | New Mexico | Oklahoma | Texas
    'region6': ['AR', 'LA', 'NM', 'OK', 'TX'],
    #Iowa | Kansas | Missouri | Nebraska
    'region7': ['IA', 'KS', 'MO', 'NE'],
    #Colorado | Montana | North Dakota | South Dakota | Utah | Wyoming
    'region8': ['CO', 'MT', 'ND', 'SD', 'UT','WY'],
    #Arizona | California | Hawaii | Nevada | Guam | American Samoa | Commonwealth of Northern Mariana Islands | Republic of Marshall Islands | Federated States of Micronesia
    'region9': ['AZ', 'CA', 'HI', 'NV', 'GU', 'AS', 'MP'],
    #Alaska | Idaho | Oregon | Washington
    'region10':['AK', 'ID', 'OR', 'WA']
}

df = pd.read_csv('../data/locations_inspectionscores_forMeri_Feb.csv')
df

,DEVELOPMENT_ID,DEVELOPMENT_NAME,CBSA_CODE,COUNTY_NAME,COUNTY_CODE,STATE_NAME.x,STATE_CODE,ZIPCODE,LATITUDE,LONGITUDE,PHA_CODE,INSPECTION_SCORE,distance_to_floodzone,in_floodplain,census_code,block_group,county,inspection_year
0,LA130000001,Duson Housing Authority,29180.0,Lafayette,55.0,LA,22,70529.0,30.239980,-92.180929,LA130,66.0,2992.337961,0.0,2.205500e+14,2.205500e+11,22055.0,2013.0
1,GA006000772,CENTENNIAL PLACE III,12060.0,Fulton,121.0,GA,13,30313.0,33.768702,-84.394727,GA006,91.0,14016.674280,0.0,1.312100e+14,1.312100e+11,13121.0,2013.0
2,GA006000770,CENTENNIAL PLACE I,12060.0,Fulton,121.0,GA,13,30313.0,33.768652,-84.392906,GA006,90.0,13985.890300,0.0,1.312100e+14,1.312100e+11,13121.0,2013.0
3,DC001001830,SCATTERED SITES,47900.0,District Of Columbia,1.0,DC,11,20001.0,38.906725,-77.014991,DC001,69.0,4377.215324,0.0,1.100100e+14,1.100100e+11,11001.0,2014.0
4,CA019000180,SCATTERED SITES,40140.0,San Bernardino,71.0,CA,6,92307.0,34.511681,-117.179101,CA019,84.0,366145.436500,0.0,6.071010e+13,6.071010e+10,6071.0,2013.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53759,WI214000001,STOUGHTON HSG/SCAT SITES,31540.0,Dane,25.0,WI,55,53589.0,42.915667,-89.200444,WI214,41.0,8111.980157,0.0,5.502501e+14,5.502501e+11,55025.0,2020.0
53760,WV011000001,DORSEY ST/BURLEY/FRANCINE/KERMIT/GATTSCT,48540.0,Marshall,51.0,WV,54,26041.0,39.916098,-80.746791,WV011,74.0,151.172824,0.0,5.405102e+14,5.405102e+11,54051.0,2020.0
53761,PA001000044,FINELLO PAVILION,38300.0,Allegheny,3.0,PA,42,15213.0,40.434161,-79.960029,PA001,57.0,16956.412360,0.0,4.200304e+14,4.200304e+11,42003.0,2020.0
53762,LA013000013,ACRE ROAD PROJECT,35380.0,Jefferson,51.0,LA,22,70072.0,29.886046,-90.116897,LA013,56.0,2487.236365,0.0,2.205103e+14,2.205103e+11,22051.0,2020.0
53763,TN040000001,WILLOW COURTS,99999.0,Henderson,77.0,TN,47,38351.0,35.655754,-88.403674,TN040,87.0,315.973737,0.0,4.707798e+14,4.707798e+11,47077.0,2020.0

In [ ]:
HEADER_STATE = ['state', 'count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']

In [10]:
stat_file = open('../figures/stats_inspection_score_year.csv', 'w') 
stat_writer = csv.writer(stat_file)    
stat_writer.writerow(HEADER_YEAR)
inspection_score = df['INSPECTION_SCORE']
stats = inspection_score.describe().round(NUM_DECIMAL).to_list()
stats.insert(0, 'overall')
stat_writer.writerow(stats)
all_years = sorted(list(set(df['inspection_year'].astype(np.double))))
all_years.remove(2005)

In [11]:
for yr in all_years:
    inspection_score_each = df.loc[df['inspection_year'] == yr]['INSPECTION_SCORE']
        
    stats_each = inspection_score_each.describe().round(NUM_DECIMAL).to_list()
        
    stats_each.insert(0, yr)
        
    stat_writer.writerow(stats_each)
    
    #close the file
stat_file.close()

In [14]:
all_states = sorted(list(set(df['STATE_NAME.x'])))

    #statistic CSV table -- by state
stat_file = open('../figures/stats_inspection_score_state.csv', 'w') 
    
stat_writer = csv.writer(stat_file)
    
stat_writer.writerow(HEADER_STATE)

    #each-state inspection score statistics
for st in all_states:
    inspection_score_each = df.loc[df['STATE_NAME.x'] == st]['INSPECTION_SCORE']

    stats_each = inspection_score_each.describe().round(NUM_DECIMAL).to_list()
        
    stats_each.insert(0, st)
        
    stat_writer.writerow(stats_each)
    
stat_file.close()

NameError: name 'HEADER_STATE' is not defined